Fixes for PHP 7.3 (#2887)
* Escape literal hyphens in character classes 8d7df427e81cdd654ba4a61e5ca3087eaec89489

PHP 7.3 uses PCRE2, which requires hyphens to be escaped unless they either symbolize a character range or occur at the beginning or end of a character class. Otherwise PHP will throw "Compilation failed: invalid range in character class at offset ...".

Escaping is backwards-compatible.

* Rename class "JSONException" to prevent clash 880a6085f39afd5a184d6f0c78ea9e445b363bfa

PHP 7.3 introduces a "JSONException" class, so we must rename ours in order to prevent the following error: "Cannot declare class JSONException, because the name is already in use ...".

This commit also updates the Composer `ClassLoader.php`.

* Revert "Rename class "JSONException" to prevent clash" 165238ba8688d27da7e078f7ed201485c7096ae9

This reverts commit 880a6085f39afd5a184d6f0c78ea9e445b363bfa.

* Fix for PHP7.3: JSONException is now native 7139b56b5c329145c87efe960b6597ebc6848680

This commits makes sure we do not load our custom JSONException class if
a native implementation already exists.

* Update PHP requirements 71108e57a0c8ff094a18e392e089f2cc414dcdca